config/routes.rb
BundesligaTipGame::Application.routes.draw do
  root :to => "home#index"

  ActiveAdmin.routes(self)

  resources :messages, :userhelper
  
  resources :news

  resources :teams do
    get "join", :on => :collection
    get "exit", :on => :collection
  end

  resources :rankings

  resources :statistiks

  devise_for :users, :skip => [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session

    get 'register' => 'devise/registrations#new', as: :new_user_registration
    get 'profile' => 'devise/registrations#edit', as: :edit_user_registration
  end
  
  match 'users/:id' => 'users#show'

  get "wsdl/update_and_evaluate"
  get "wsdl/get_all_for_new_saison"
  get "wsdl/get_teams_by_league_saison"
  get "wsdl/get_current_group"

  get "getusers/show"
  get "getusers/get"

  get "start/index"
  match "start" => "start#index"

  get "start/tipp"
  match "tipp" => "start#tipp"
  post "start/tipp"
  match "tipp" => "start#tipp"

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
      if user.has_role? :admin
        # Adminis
        can :manage, :all
      else if user.has_role? :user
        # Registered users
        can :manage, :all
        cannot :create,  News
        cannot :update,  News
        cannot :destroy,  News
        cannot :manage, Admin
      else
        can :manage, :home
      end
    end
  end
end
#
# The first argument to `can` is the action you are giving the user permission to do.
# If you pass :manage it will apply to every action. Other common actions here are
# :read, :create, :update and :destroy.
#
# The second argument is the resource the user can perform the action on. If you pass
# :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
#
# The third argument is an optional hash of conditions to further filter the objects.
# For example, here the user can only update published articles.
#
#   can :update, Article, :published => true
#
# See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :news_categories
  has_many :categories, through: :news_categories
  validates_uniqueness_of :name
end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :group_id, :group_name, :group_order_id, :icon_url_team1, :icon_url_team2, :id_team1, :id_team2, :last_update, :league_id, :league_name, :league_saison, :league_shortcut, :match_date_time, :match_date_time_utc, :match_is_finished, :match_number, :name_team2, :name_team1, :points_team1, :points_team2, :time_zone_id
  validates_uniqueness_of :match_number

  has_many :tipps
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :content, :title, :user_id, :category_ids
  has_many :news_categories
  has_many :categories, through: :news_categories
  belongs_to :user
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  attr_accessible :author, :title
end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  attr_accessible :league_id, 
									:league_short, 
									:league_saison, 
									:last_change, 
									:color_body, 
									:color_input, 
									:color_input_border, 
									:color_input_shadow, 
									:color_input_border_hover, 
									:color_input_shadow_hover, 
									:color_input_border_focus, 
									:color_input_shadow_focus, 
									:color_input_submit,
									:color_input_submit_background_top,
									:color_input_submit_background_bottom,
									:color_input_submit_background_hover,
									:color_title,
									:color_main,
									:color_main_h2,
									:color_main_h3,
									:color_notice_background,
									:color_alert_background
end

app/models/soccerteam.rb
class Soccerteam < ActiveRecord::Base
  attr_accessible :team_icon_url, :team_name, :team_number
  validates_uniqueness_of :team_number
end

app/models/statistik.rb
class Statistik < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name, :owner_id, :is_public, :points
  validates :name, presence: true
  validates_uniqueness_of :name
  has_many :users
end

app/models/tipp.rb
class Tipp < ActiveRecord::Base
  attr_accessible :points, :team1, :team2, :user_id, :match_id, :checked

  belongs_to :user
  belongs_to :match
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable,
  # :lockable, :timeoutable, :omniauthable, :confirmable,
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :firstname, :lastname, :birthday, :role_ids
  
  validates_uniqueness_of :username
  validates_presence_of :email, :encrypted_password, :username, :firstname, :lastname, :birthday

  belongs_to :team
  has_many :tipps
  has_many :user_messages
  has_many :messages, :through => :user_messages
  has_many :news

  before_create :set_default_role

  private
  def set_default_role
    self.add_role :user
  end

end

app/models/user_message.rb
class UserMessage < ActiveRecord::Base
  belongs_to :user
  belongs_to :message
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  load_and_authorize_resource :only => [:index, :show]
  # GET /messages
  # GET /messages.json
  def index
    to = current_user.user_messages.select(:message_id)
    to_array = Array.new
    to.each do |u|
      to_array << u.message_id
    end
    @inbox = Message.where(id: to_array)
    @outbox = Message.where(from: current_user.id)
    #@messages = Message.where(to: current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end 
  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new
    # if !params[:to].nil?
    #   params[:to].each do |p|
    #     #@message.to.push(User.find(p))
    #     @message.users.push(User.find(p))
    #   end
    # end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])
    @message.from = current_user.id

    m = params[:message]
    @message.users = Array.new
    m[:user_ids].to_s.split(',').each {|i| @message.users << User.find(i) }
      
    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_path, notice: 'Message was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tipps_helper.rb
module TippsHelper
end

app/helpers/wsdl_helper.rb
module WsdlHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :to, "To:" %><br />  
    <%= f.text_field :user_ids %>      
  </div>
  <div class="field">
    <%= f.label :title, "Subject:" %><br />  
    <%= f.text_field :title %>  
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Send" %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Messages</h1>
<div id="tabs">
  <ul>
    <li><a href="#tabs-1">Inbox</a></li>
    <li><a href="#tabs-2">Outbox</a></li>
  </ul>
  <div id="tabs-1">
    <p>
    <table width="100%">
      <% @inbox.each do |message| %>
      <tr class="row">
        <!--  # Sucht nach der ID ! -->
        <td width="30%">Von: <%= User.find(message.from).username %></td>
        <td>Betreff: <%= message.title %></td>
        <td width="20px"><%= link_to image_tag('icons/down.png'), '#message_' + message.id.to_s, onclick: 'Application.showContent(this, ' + message.id.to_s + ')' %></td>
      </tr>
      <tr>
        <td id="message_<%= message.id %>" style="display:none" colspan="2">
          <%= message.content %><br /><br /><br />
          <!-- Übergibt from_id an das neue To Feld -->
          <%= link_to "Antworten", new_message_path(:to => message.from) %><br /><br />
        </td>
      </tr>
      <% end %>
    </table>
    </p>
  </div>
  <div id="tabs-2">
    <p>
    <table width="100%">
      <% @outbox.each do |message| %>
      <tr>
        <!--  # Sucht nach der ID ! -->
        <td width="30%">
          An: 
          <% to = "" 
            UserMessage.where(message_id: message.id).each do |u|
              to += User.find(u.user_id).username + ", "
            end
            to = to[0..-2]
          %>
          <%= to[0..-2] %>
        </td>
        <td>Betreff: <%= message.title %></td>
        <td width="20px"><%= link_to image_tag('icons/down.png'), '#message_' + message.id.to_s, onclick: 'Application.showContent(this, ' + message.id.to_s + ')' %></td>
      </tr>
      <tr>
        <td id="message_<%= message.id %>" style="display:none" colspan="2">
          <%= message.content %>
        </td>
      </tr>
      <% end %>
    </table>
    </p>
  </div>
</div>
<br />
<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<div id="content_holder">
	<h1>New message</h1>

	<%= render 'form' %>

	<%= link_to 'Back', messages_path %>
</div>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>From:</b>
  <%= @message.from %>
</p>

<p>
  <b>To:</b>
  <%= @message.to %>
</p>

<p>
	<b>Subject:</b>
	<%= @message.title %>
</p>

<p>
  <b>Content:</b>
  <%= @message.content %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>