config/routes.rb
BundesligaTipGame::Application.routes.draw do
  root :to => "home#index"

  ActiveAdmin.routes(self)

  resources :messages, :userhelper
  
  resources :news

  resources :teams do
    get "join", :on => :collection
    get "exit", :on => :collection
  end

  resources :rankings

  resources :statistiks

  devise_for :users, :skip => [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session

    get 'register' => 'devise/registrations#new', as: :new_user_registration
    get 'profile' => 'devise/registrations#edit', as: :edit_user_registration
  end
  
  match 'users/:id' => 'users#show'

  get "wsdl/update_and_evaluate"
  get "wsdl/get_all_for_new_saison"
  get "wsdl/get_teams_by_league_saison"
  get "wsdl/get_current_group"

  get "getusers/show"
  get "getusers/get"

  get "start/index"
  match "start" => "start#index"

  get "start/tipp"
  match "tipp" => "start#tipp"
  post "start/tipp"
  match "tipp" => "start#tipp"

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
      if user.has_role? :admin
        # Adminis
        can :manage, :all
      else if user.has_role? :user
        # Registered users
        can :manage, :all
        cannot :create,  News
        cannot :update,  News
        cannot :destroy,  News
        cannot :manage, Admin
      else
        can :manage, :home
      end
    end
  end
end
#
# The first argument to `can` is the action you are giving the user permission to do.
# If you pass :manage it will apply to every action. Other common actions here are
# :read, :create, :update and :destroy.
#
# The second argument is the resource the user can perform the action on. If you pass
# :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
#
# The third argument is an optional hash of conditions to further filter the objects.
# For example, here the user can only update published articles.
#
#   can :update, Article, :published => true
#
# See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :news_categories
  has_many :categories, through: :news_categories
  validates_uniqueness_of :name
end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :group_id, :group_name, :group_order_id, :icon_url_team1, :icon_url_team2, :id_team1, :id_team2, :last_update, :league_id, :league_name, :league_saison, :league_shortcut, :match_date_time, :match_date_time_utc, :match_is_finished, :match_number, :name_team2, :name_team1, :points_team1, :points_team2, :time_zone_id
  validates_uniqueness_of :match_number

  has_many :tipps
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :content, :title, :user_id, :category_ids
  has_many :news_categories
  has_many :categories, through: :news_categories
  belongs_to :user
end

app/models/news_category.rb
class NewsCategory < ActiveRecord::Base
  attr_accessible :news, :category
  belongs_to :news
  belongs_to :category
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  attr_accessible :author, :title
end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  attr_accessible :league_id, 
									:league_short, 
									:league_saison, 
									:last_change, 
									:color_body, 
									:color_input, 
									:color_input_border, 
									:color_input_shadow, 
									:color_input_border_hover, 
									:color_input_shadow_hover, 
									:color_input_border_focus, 
									:color_input_shadow_focus, 
									:color_input_submit,
									:color_input_submit_background_top,
									:color_input_submit_background_bottom,
									:color_input_submit_background_hover,
									:color_title,
									:color_main,
									:color_main_h2,
									:color_main_h3,
									:color_notice_background,
									:color_alert_background
end

app/models/soccerteam.rb
class Soccerteam < ActiveRecord::Base
  attr_accessible :team_icon_url, :team_name, :team_number
  validates_uniqueness_of :team_number
end

app/models/statistik.rb
class Statistik < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name, :owner_id, :is_public, :points
  validates :name, presence: true
  validates_uniqueness_of :name
  has_many :users
end

app/models/tipp.rb
class Tipp < ActiveRecord::Base
  attr_accessible :points, :team1, :team2, :user_id, :match_id, :checked

  belongs_to :user
  belongs_to :match
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable,
  # :lockable, :timeoutable, :omniauthable, :confirmable,
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :firstname, :lastname, :birthday, :role_ids
  
  validates_uniqueness_of :username
  validates_presence_of :email, :encrypted_password, :username, :firstname, :lastname, :birthday

  belongs_to :team
  has_many :tipps
  has_many :user_messages
  has_many :messages, :through => :user_messages
  has_many :news

  before_create :set_default_role

  private
  def set_default_role
    self.add_role :user
  end

end

app/models/user_message.rb
class UserMessage < ActiveRecord::Base
  belongs_to :user
  belongs_to :message
end

app/controllers/start_controller.rb
require "webservice"

class StartController < ApplicationController
  load_and_authorize_resource :class => false

  def index
    @news = News.last
  end

  def tipp
  	if params.has_key?(:group_id_for_save)
  		tipp_save
  	# Begegnungen anzeigen
  	else
      @setting = Setting.first
  		# Spieltag herausfinden, entweder als Paramter übergeben, oder vom WebService holen
  		if params.has_key?(:g)
  			group_id = params[:g]
  		else
		  	group_id = @setting.current_group_id
        #group_id = WsdlController.new.get_current_group
		  end

		  # Alle Spiele eines Spieltages holen
	  	@matches = Match.where("group_order_id = ?", group_id).order("match_date_time ASC")
  	end
  end

  def tipp_save
  	current_matches = Match.where("group_order_id = ?", params[:group_id_for_save])
  	current_matches.each do |m|

  		team1 = params[m.match_number.to_s + "_" + m.id_team1.to_s]
  		team2 = params[m.match_number.to_s + "_" + m.id_team2.to_s]

  		# Wenn team1 und 2 Eingaben haben, dann werden sie gepeichert
  		if !team1.blank? and !team2.blank?
				tipp = Tipp.new
  			
  			# schauen ob schon ein Tipp für dieses Spiel vorhanden ist
  			# wenn vorhanden, dann diesen bearbeiten und dann speichern
  			current_tipp = Tipp.where("user_id = ? and match_id = ?", current_user.id, m.id)
  			if current_tipp.size > 0
	  			tipp = current_tipp.first
	  		end
	  		
	  		tipp.team1 = team1.to_i
	  		tipp.team2 = team2.to_i
	  		tipp.points = 0
	  		tipp.user_id = current_user.id
	  		tipp.match_id = m.id

	  		tipp.save
	  	end
  	end
  	
  	redirect_to tipp_path(:g => params[:group_id_for_save])
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tipps_helper.rb
module TippsHelper
end

app/helpers/wsdl_helper.rb
module WsdlHelper
end

app/views/start/_ranking_team.html.erb
<h3>Die besten Teams</h3>
<!-- Team-Ranking -->
<% Team.find(:all, order: "points DESC", limit: 10).each do |t| %>
	<div class="row">
		<div style="width:50%; float:left">
			<%=	t.name %>
		</div>
		<div style="width:20%; float:right; text-align: right;">
			<%= t.points.to_i %> Pkt.
		</div>
		<div style="clear:both"></div>
	</div>
<% end %>

app/views/start/index.html.erb
<!-- http://www.iconfinder.com/search/?q=iconset%3Acc_mono_icon_set -->
<ul class="content_fontcolor_link">
	<li style="background-image: url(<%= asset_path 'icons/check.png' %>);">
		<h2><%= link_to "Meine Tipps", tipp_path %></h2>
		<p>Gebe hier deine Tipps für die n&auml;chsten Spiele ab!</p>
	</li>
	<li style="background-image: url(<%= asset_path 'icons/group.png' %>);">
		<h2><%= link_to "Meine Tippgemeinschaft", teams_path %></h2>
		<p>Wie gut bist du in deiner Tippgemeinschaft?</p>
	</li>
	<li style="background-image: url(<%= asset_path 'icons/number_list.png' %>);">
		<h2><%= link_to "Ranking", rankings_path %></h2>
		<p>Hier siehst du, wie gut du und deine Tippgemeinschaft sind!</p>
	</li>
	<li style="background-image: url(<%= asset_path 'icons/statistics.png' %>);">
		<h2><%= link_to "Statistik", statistiks_path %></h2>
		<p>Aktuelle Tabelle</p>
	</li>
	<li style="background-image: url(<%= asset_path 'icons/profil.png' %>);">
		<h2><%= link_to "Mein Profil", edit_user_registration_path %></h2>
		<p>Bearbeite hier dein Profil!</p>
	</li>
	<li style="background-image: url(<%= asset_path 'icons/mail.png' %>);">
		<h2><%= link_to "Nachrichten", messages_path %></h2>
		<p>Kommuniziere mit deinen Freunden!</p>
	</li>
</ul>
<br style="clear:both">

<% if !@news.nil? %>
<div id="content_holder">
	<h1><%= link_to 'Neuigkeiten', news_index_path %></h1>
	<br/>
	<br/> 
	<article>
	  <h2><%= link_to @news.title, @news %></h2>
	  <p class="news_categories">Autor: <%= @news.user.username %> Datum: <%= @news.created_at.strftime("%d.%m.%Y %H:%M") %></p>
	  <p class="news_content"><%= raw(@news.content) %></p>
	  <p class="news_categories">Kategorien: 
	    <% @CategoryString = "" %>
	    <% @news.category_ids.each do |n| %>
	      <% @CategoryString += Category.find(n).name + ", " %>
	    <% end %>
	    <%= @CategoryString[0..-3] %>
	  </p>
	</article>
</div>
<% end %>

app/views/start/ranking.html.erb
<div id="content_holder">

	<%= render "ranking_user" %>
	<br><br>
	<%= render "ranking_team" %>
</div>

app/views/start/statistik.html.erb
<div id="content_holder_big">
	<h3>Aktuelle Bundesligatabelle</h3>
	<!-- Bundesligatabelle -->
	<div class="row">
		<div class="div_table_numbers">
			Pl.
		</div>
		<div class="div_table_name">
			Verein
		</div>
		<div class="div_table_numbers">&nbsp;</div>
		<div class="div_table_numbers">
			Sp.
		</div>
		<div class="div_table_numbers">&nbsp;</div>
		<div class="div_table_numbers">
			g.
		</div>
		<div class="div_table_numbers">
			u.
		</div>
		<div class="div_table_numbers">
			v.
		</div>
		<div class="div_table_numbers">&nbsp;</div>
		<div class="div_table_numbers">
			Tore
		</div>
		<div class="div_table_numbers">&nbsp;</div>
		<div class="div_table_numbers">
			Diff.
		</div>
		<div class="div_table_numbers">&nbsp;</div>
		<div class="div_table_numbers">
			Pkt.
		</div>
		<div style="clear:both"></div>
	</div>
	<% position = 0 %>
	<% Soccerteam.select("*, (goals_for + goals_against) as diff").order("points DESC, diff DESC, goals_for DESC").each do |t| %>
	<% #Soccerteam.(:all, order: "points DESC", limit: 10).each do |t| %>
		<% position += 1 %>
		<div class="row">
			<div class="div_table_numbers">
				<%=	position %>
			</div>
			<div class="div_table_name">
				<img src="<%=	t.team_icon_url %>" />
				<%=	t.team_name %>
			</div>
			<div class="div_table_numbers">&nbsp;</div>
			<div class="div_table_numbers">
				<%=	t.played_matches %>
			</div>
			<div class="div_table_numbers">&nbsp;</div>
			<div class="div_table_numbers">
				<%=	t.win %>
			</div>
			<div class="div_table_numbers">
				<%=	t.drawn %>
			</div>
			<div class="div_table_numbers">
				<%=	t.lost %>
			</div>
			<div class="div_table_numbers">&nbsp;</div>
			<div class="div_table_numbers">
				<%=	t.goals_for %>:<%= t.goals_against %>
			</div>
			<div class="div_table_numbers">&nbsp;</div>
			<div class="div_table_numbers">
				<%=	t.goals_for - t.goals_against %>
			</div>
			<div class="div_table_numbers">&nbsp;</div>
			<div class="div_table_numbers">
				<%= t.points.to_i %>
			</div>
			<div style="clear:both"></div>
		</div>
	<% end %>
</div>

app/views/start/tipp.html.erb
<div id="content_holder">
	<% if !@matches.empty? %>
		<%= form_tag "/tipp", method: "get" do %>
			<div style="text-align:center; margin-bottom:15px;"><h2><%= @matches[0][:group_name] %></h2></div>
			<table width="100%">
				<% current_tipps = Tipp.where("user_id = ?", current_user.id) %>
				<%= hidden_field_tag "group_id_for_save", @matches[0].group_order_id %>
				<% @matches.each do |m| %>
					<tr>
						<td>
							<%= m.name_team1 %>
						</td>
						<td>
							<% 
								current_tipp = current_tipps.find_by_match_id(m.id) 
								current_tipp_team1 = "-"
								current_tipp_team2 = "-"
								if !current_tipp.nil?
									current_tipp_team1 = current_tipp[:team1]
									current_tipp_team2 = current_tipp[:team2]
								end
							%>
							<% if DateTime.now > DateTime.parse((m.match_date_time_utc - 15.minutes).to_s) %>
								<table class="table_tipps">
									<tr>
										<td class="match_result_left">
											<%= label_tag current_tipp_team1 %>
										</td>
										<td class="match_result_center">
											:
										</td>
										<td class="match_result_right">
											<%= label_tag current_tipp_team2 %>
										</td>
									</tr>
									<% if m.match_is_finished? %>
										<tr class="match_result">
											<td class="match_result_left">
												<%= label_tag m.points_team1 %>
											</td>
											<td class="match_result_center">
												:
											</td>
											<td class="match_result_right">
												<%= label_tag m.points_team2 %>
											</td>
										</tr>
									<% end %>
								</table>
							<% else %>
								<table width="100%">
									<tr>
										<td class="match_result_left">
											<%= number_field_tag m.match_number.to_s + "_" + m.id_team1.to_s, 
																		current_tipp_team1, 
																		min: 0, 
																		style: "width:25px;" %>
										</td>
										<td class="match_result_center">
											:
										</td>
										<td class="match_result_right">
											<%= number_field_tag m.match_number.to_s + "_" + m.id_team2.to_s, 
																		current_tipp_team2, 
																		min: 0, 
																		style: "width:25px;" %>
										</td>
									</tr>
								</table>
							<% end %>
						</td>
						<td>
							<%= m.name_team2 %>
						</td>
					</tr>
				<% end %>
			</table>	
			<%= submit_tag "Speichern" %>
		<% end %>
		<div>
			Spieltag: <br />
			<% Match.select(:group_order_id).order("group_order_id ASC").uniq.each do |m| %>
				<% if m.group_order_id == @setting.current_group_id %>
					<span style="font-weight:bolder"><%= link_to m.group_order_id, tipp_path(:g => m.group_order_id.to_s) %></span>
				<% else %>
			  	<%= link_to m.group_order_id, tipp_path(:g => m.group_order_id.to_s) %> 
			  <% end %> | 
			<% end %>
		</div>
<% else %>
	<p>Es ist ein unbekannter Fehler aufgetreten!</p>
<% end %>
</div>