config/routes.rb
BundesligaTipGame::Application.routes.draw do
  root :to => "home#index"

  ActiveAdmin.routes(self)

  resources :messages, :userhelper
  
  resources :news

  resources :teams do
    get "join", :on => :collection
    get "exit", :on => :collection
  end

  resources :rankings

  resources :statistiks

  devise_for :users, :skip => [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session

    get 'register' => 'devise/registrations#new', as: :new_user_registration
    get 'profile' => 'devise/registrations#edit', as: :edit_user_registration
  end
  
  match 'users/:id' => 'users#show'

  get "wsdl/update_and_evaluate"
  get "wsdl/get_all_for_new_saison"
  get "wsdl/get_teams_by_league_saison"
  get "wsdl/get_current_group"

  get "getusers/show"
  get "getusers/get"

  get "start/index"
  match "start" => "start#index"

  get "start/tipp"
  match "tipp" => "start#tipp"
  post "start/tipp"
  match "tipp" => "start#tipp"

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
      if user.has_role? :admin
        # Adminis
        can :manage, :all
      else if user.has_role? :user
        # Registered users
        can :manage, :all
        cannot :create,  News
        cannot :update,  News
        cannot :destroy,  News
        cannot :manage, Admin
      else
        can :manage, :home
      end
    end
  end
end
#
# The first argument to `can` is the action you are giving the user permission to do.
# If you pass :manage it will apply to every action. Other common actions here are
# :read, :create, :update and :destroy.
#
# The second argument is the resource the user can perform the action on. If you pass
# :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
#
# The third argument is an optional hash of conditions to further filter the objects.
# For example, here the user can only update published articles.
#
#   can :update, Article, :published => true
#
# See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :news_categories
  has_many :categories, through: :news_categories
  validates_uniqueness_of :name
end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :group_id, :group_name, :group_order_id, :icon_url_team1, :icon_url_team2, :id_team1, :id_team2, :last_update, :league_id, :league_name, :league_saison, :league_shortcut, :match_date_time, :match_date_time_utc, :match_is_finished, :match_number, :name_team2, :name_team1, :points_team1, :points_team2, :time_zone_id
  validates_uniqueness_of :match_number

  has_many :tipps
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :content, :title, :user_id, :category_ids
  has_many :news_categories
  has_many :categories, through: :news_categories
  belongs_to :user
end

app/models/news_category.rb
class NewsCategory < ActiveRecord::Base
  attr_accessible :news, :category
  belongs_to :news
  belongs_to :category
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  attr_accessible :author, :title
end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  attr_accessible :league_id, 
									:league_short, 
									:league_saison, 
									:last_change, 
									:color_body, 
									:color_input, 
									:color_input_border, 
									:color_input_shadow, 
									:color_input_border_hover, 
									:color_input_shadow_hover, 
									:color_input_border_focus, 
									:color_input_shadow_focus, 
									:color_input_submit,
									:color_input_submit_background_top,
									:color_input_submit_background_bottom,
									:color_input_submit_background_hover,
									:color_title,
									:color_main,
									:color_main_h2,
									:color_main_h3,
									:color_notice_background,
									:color_alert_background
end

app/models/soccerteam.rb
class Soccerteam < ActiveRecord::Base
  attr_accessible :team_icon_url, :team_name, :team_number
  validates_uniqueness_of :team_number
end

app/models/statistik.rb
class Statistik < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name, :owner_id, :is_public, :points
  validates :name, presence: true
  validates_uniqueness_of :name
  has_many :users
end

app/models/tipp.rb
class Tipp < ActiveRecord::Base
  attr_accessible :points, :team1, :team2, :user_id, :match_id, :checked

  belongs_to :user
  belongs_to :match
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable,
  # :lockable, :timeoutable, :omniauthable, :confirmable,
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :firstname, :lastname, :birthday, :role_ids
  
  validates_uniqueness_of :username
  validates_presence_of :email, :encrypted_password, :username, :firstname, :lastname, :birthday

  belongs_to :team
  has_many :tipps
  has_many :user_messages
  has_many :messages, :through => :user_messages
  has_many :news

  before_create :set_default_role

  private
  def set_default_role
    self.add_role :user
  end

end

app/models/user_message.rb
class UserMessage < ActiveRecord::Base
  belongs_to :user
  belongs_to :message
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  load_and_authorize_resource
  # GET /news
  # GET /news.json
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(params[:news])
    @news.user_id = current_user.id

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/getusers_helper.rb
module GetusersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tipps_helper.rb
module TippsHelper
end

app/helpers/wsdl_helper.rb
module WsdlHelper
end

app/views/news/_form.html.erb
<%= javascript_include_tag "tiny_mce/tiny_mce.js" %>
  <%= csrf_meta_tags %>
  <%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>
      <ul>
        <% @news.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= 'Titel: ' %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= 'Inhalt: ' %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= 'Kategorien (Mehrfachauswahl möglich): ' %><br />
    <%= f.collection_select :category_ids, Category.all, :id, :name, {selected: @news.category_ids}, {multiple: true} %>
  </div>
  <div class="actions">
    <%= f.submit 'Speichern' %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>News bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @news %> |
<%= link_to 'Zurück', news_index_path %>

app/views/news/index.html.erb
<h1>Neuigkeiten</h1>
<% if can? :create, @news %>
  <%= link_to 'Neue News', new_news_path %>
<% end %>
<br/>
<br/> 
<% @news.each do |news| %>
  <article>
    <div class="news_actions">
      <% if can? :update, news %>
        <%= link_to 'Bearbeiten', edit_news_path(news) %>
      <% end %>
      <% if can? :destroy, news %>
        <%= link_to 'Löschen', news, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
    <h2><%= link_to news.title, news %></h2>
    <p class="news_categories">Autor: <%= news.user.username %> Datum: <%= news.created_at.strftime("%d.%m.%Y %H:%M") %></p>
    <p class="news_content"><%= raw(news.content) %></p>
    <p class="news_categories">
      <% @CategoryString = "" %>
      <% news.category_ids.each do |n| %>
         <% @CategoryString += Category.find(n).name + ", " %>
      <% end %>
      Kategorien: <%= @CategoryString[0..-3] %>
    </p>
  </article>
<% end %>

app/views/news/new.html.erb
<h1>News erstellen</h1>

<%= render 'form' %>

<%= link_to 'Zurück', news_index_path %>

app/views/news/show.html.erb
<h1><%= link_to 'Neuigkeiten', news_index_path %></h1>
<% if can? :create, @news %>
  <%= link_to 'Neue News', new_news_path %>
<% end %>
<br/>
<br/> 
<article>
  <div class="news_actions">
    <% if can? :update, @news %>
      <%= link_to 'Bearbeiten', edit_news_path(@news) %>
    <% end %>
    <% if can? :destroy, @news %>
      <%= link_to 'Löschen', @news, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
  <h2><%= link_to @news.title, @news %></h2>
  <p class="news_categories">Autor: <%= @news.user.username %> Datum: <%= @news.created_at.strftime("%d.%m.%Y %H:%M") %></p>
  <p class="news_content"><%= raw(@news.content) %></p>
  <p class="news_categories">Kategorien: 
    <% @CategoryString = "" %>
    <% @news.category_ids.each do |n| %>
      <% @CategoryString += Category.find(n).name + ", " %>
    <% end %>
    <%= @CategoryString[0..-3] %>
  </p>
</article>